require 'ruby-band/weka/db/db'
require 'ruby-band/weka/filters/unsupervised/attribute/attribute'
require 'ruby-band/weka/filters/unsupervised/instance/instance'
require 'ruby-band/weka/filters/supervised/instance/instance'
require 'ruby-band/weka/filters/supervised/attribute/attribute'
require 'ruby-band/weka/classifiers/bayes/bayes'
require 'ruby-band/weka/classifiers/evaluation'
require 'ruby-band/weka/classifiers/evaluation/threshold_curve'
require 'ruby-band/weka/classifiers/functions/functions'
requ